package com.wkhtmltopdf;

public class MainTest {

	public static void main(String[] args) {
		String html = "<!DOCTYPE html>\n" + "<html>\n" + " <head> \n"
				+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> \n"
				+ "  <meta charset=\"utf-8\"> \n"
				+ "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=no,maximum-scale=1.0\"> \n"
				+ "  <title>Migraine Listing</title> \n" + "  <style type=\"text/css\">\n" + "\n"
				+ "* {\n" + "    padding: 0;\n" + "    margin: 0;\n" + "    color: #3f798c;\n"
				+ "    font-family: 'Asap', sans-serif;\n" + "}\n" + ".main-header {\n"
				+ "    margin: 1em auto 0 auto;\n" + "    max-width: 1024px;\n"
				+ "    box-sizing: border-box;\n" + "    margin-top: 15px;\n"
				+ "    margin-bottom: 20px;\n" + "    display: flex;\n"
				+ "    justify-content: flex-start;\n" + "}\n" + "\n" + "header img {\n"
				+ "    vertical-align: middle;\n" + "}\n" + "\n" + "/* Legend */\n"
				+ ".main-header .icon {\n" + "    margin: auto 0px;\n" + "}\n" + "\n"
				+ ".main-header img {\n" + "    vertical-align: middle;\n"
				+ "    padding-right: 50px;\n" + "}\n" + "\n" + "/* Table CSS */\n" + "\n"
				+ "#overview {\n" + "    max-width: 400px;\n" + "    margin: 1em auto 0 auto;\n"
				+ "    padding:10px;\n" + "\n" + "    -moz-border-radius-bottomleft:3px;\n"
				+ "    border-bottom-left-radius:3px;\n" + "\n"
				+ "    -moz-border-radius-bottomright:3px;\n"
				+ "    border-bottom-right-radius:3px;\n" + "\n"
				+ "    -moz-border-radius-topright:3px;\n" + "    border-top-right-radius:3px;\n"
				+ "\n" + "    -moz-border-radius-topleft:3px;\n"
				+ "    border-top-left-radius:3px;\n" + "\n"
				+ "    -webkit-print-color-adjust: exact;\n" + "}\n" + "\n" + "\n"
				+ "#overview table {\n" + "    border-collapse: collapse;\n"
				+ "    border-spacing: 0;\n" + "    width:100%;\n" + "    margin:0px;\n"
				+ "    padding:0px;\n" + "    border:1px solid #c3d8d8;\n"
				+ "    background-color:#ffffff;\n" + "}\n" + "\n" + "#overview tr {\n"
				+ "    width: 100%;\n" + "}\n" + "\n" + "#overview td {\n"
				+ "    vertical-align:middle;\n" + "    border:1px solid #c3d8d8;\n"
				+ "    border-width:0px 1px 1px 0px;\n" + "    text-align:center;\n"
				+ "    padding:4px;\n" + "    font-size:12px;\n" + "    color:#0b2730;\n"
				+ "    max-width: 150px;\n" + "}\n" + "\n" + "#overview right-border {\n"
				+ "    border-width:0px 1px 0px 0px;\n" + "}\n" + "\n"
				+ "#overview bottom-border {\n" + "    border-width:0px 0px 1px 0px;\n" + "}\n"
				+ "\n" + "#overview bottom-left-border {\n" + "    border-width:0px 0px 1px 1px;\n"
				+ "}\n" + "\n" + "#overview .header-overview td {\n"
				+ "    background-color:#3f798c;\n" + "    border:0px solid #c3d8d8;\n"
				+ "    text-align:center;\n" + "    font-size:12px;\n"
				+ "    border-width:0px 0px 1px 1px;\n" + "    font-weight:bold;\n"
				+ "    color:#ffffff;\n" + "}\n" + "\n" + "#overview tbody tr {\n"
				+ "    height: 0px;\n" + "}\n" + "\n" + "\n" + "\n" + ".reports-table {\n"
				+ "    margin: 1em auto 0 auto;\n" + "    padding:10px;\n"
				+ "    min-width: 1024px;\n" + "    width: 85%;\n" + "\n"
				+ "    -moz-border-radius-bottomleft:3px;\n"
				+ "    border-bottom-left-radius:3px;\n" + "\n"
				+ "    -moz-border-radius-bottomright:3px;\n"
				+ "    border-bottom-right-radius:3px;\n" + "\n"
				+ "    -moz-border-radius-topright:3px;\n" + "    border-top-right-radius:3px;\n"
				+ "\n" + "    -moz-border-radius-topleft:3px;\n"
				+ "    border-top-left-radius:3px;\n" + "\n"
				+ "    -webkit-print-color-adjust: exact;\n" + "}\n" + "\n" + "\n"
				+ ".reports-table table {\n" + "    border-collapse: collapse;\n"
				+ "    border-spacing: 0;\n" + "    width:100%;\n" + "    margin:0px;\n"
				+ "    padding:0px;\n" + "    border:1px solid #c3d8d8;\n"
				+ "    background-color:#ffffff;\n" + "}\n" + "\n" + ".reports-table tr {\n"
				+ "    width: 100%;\n" + "}\n" + "\n" + ".reports-table td {\n"
				+ "    vertical-align:middle;\n" + "    border:1px solid #c3d8d8;\n"
				+ "    border-width:0px 1px 1px 0px;\n" + "    text-align:center;\n"
				+ "    padding:4px;\n" + "    font-size:12px;\n" + "    color:#0b2730;\n"
				+ "    max-width: 150px;\n" + "}\n" + "\n" + ".reports-table right-border {\n"
				+ "    border-width:0px 1px 0px 0px;\n" + "}\n" + "\n"
				+ ".reports-table bottom-border {\n" + "    border-width:0px 0px 1px 0px;\n" + "}\n"
				+ "\n" + ".reports-table bottom-left-border {\n"
				+ "    border-width:0px 0px 1px 1px;\n" + "}\n" + "\n"
				+ ".reports-table .header td {\n" + "    background-color:#3f798c;\n"
				+ "    border:0px solid #c3d8d8;\n" + "    text-align:center;\n"
				+ "    font-size:12px;\n" + "    border-width:0px 0px 1px 1px;\n"
				+ "    font-weight:bold;\n" + "    color:#ffffff;\n" + "}\n" + "\n"
				+ ".reports-table thead subheading {\n" + "    background-color:#5fa6be;\n" + "}\n"
				+ "\n" + ".reports-table thead subheading td{\n" + "    color:#fff;\n" + "}\n"
				+ "\n" + ".reports-table tbody tr {\n" + "    height: 0px;\n" + "}\n" + "\n"
				+ ".reports-table tr td div.helpful{\n" + "    color:#02921a;\n" + "}\n" + "\n"
				+ ".reports-info {\n" + "    margin: 1em auto 0 auto;\n" + "    padding:10px;\n"
				+ "    min-width: 1024px;\n" + "    width: 85%;\n" + "}\n" + "\n" + ".notes {\n"
				+ "    text-align: left !important;\n" + "    padding-bottom: 15px !important;\n"
				+ "}\n" + "\n" + "pre {\n" + "    white-space: pre-wrap;\n" + "}\n" + "\n"
				+ ".relief-methods {\n" + "    margin-top : 10px;\n" + "}\n" + "\n"
				+ "#printButton button {\n" + "    border: none;\n" + "    background: none;\n"
				+ "}\n" + "\n" + "\n" + "@media print {\n"
				+ "    table { page-break-inside: auto; }\n"
				+ "    tr    { page-break-inside: avoid; page-break-after: auto; }\n"
				+ "    thead { display: table-header-group; }\n"
				+ "    #printButton { display: none; }\n" + "    @page { size: landscape }\n"
				+ "}\n" + "\n" + "\n" + "\n" + "</style> \n"
				+ "  <link href=\"https://fonts.googleapis.com/css?family=Asap:400,400italic,700,700italic\" rel=\"stylesheet\" type=\"text/css\"> \n"
				+ "  <style>\n" + "    </style> \n" + " </head> \n"
				+ " <body style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "  <div class=\"main-header\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;margin:1em auto 0 auto;max-width:1024px;box-sizing:border-box;margin-top:15px;margin-bottom:20px;display:flex;justify-content:flex-start\"> \n"
				+ "   <div class=\"legend\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "    <img src=\"http://s3-ap-southeast-1.amazonaws.com/migraine-buddy-marketing/emails_assets/mb-inline-compact-double.png\" width=\"250\" alt=\"Migraine Buddy logo\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;padding-right:50px\"> \n"
				+ "   </div> \n" + "  </div> \n"
				+ "  <div class=\"reports-info\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;margin:1em auto 0 auto;padding:10px;min-width:1024px;width:85%\"> \n"
				+ "   <table style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "    <tbody style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\">\n"
				+ "     <tr style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> Attack Type: </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> <b style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\">All</b> </td> \n"
				+ "     </tr> \n" + "    </tbody>\n" + "   </table> \n" + "  </div> \n"
				+ "  <center style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "   <div class=\"overview-table\" id=\"overview\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;max-width:400px;margin:1em auto 0 auto;padding:10px;-moz-border-radius-bottomleft:3px;border-bottom-left-radius:3px;-moz-border-radius-bottomright:3px;border-bottom-right-radius:3px;-moz-border-radius-topright:3px;border-top-right-radius:3px;-moz-border-radius-topleft:3px;border-top-left-radius:3px;-webkit-print-color-adjust:exact\"> \n"
				+ "    <table style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;border-collapse:collapse;border-spacing:0;width:100%;margin:0px;padding:0px;border:1px solid rgb(195, 216, 216);background-color:rgb(255, 255, 255)\"> \n"
				+ "     <thead class=\"header-overview\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "      <tr style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;width:100%\"> \n"
				+ "       <td class=\"bottom-border\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Number of Attacks</td> \n"
				+ "       <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Attack Days</td> \n"
				+ "       <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Attack-Free Days</td> \n"
				+ "       <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Avg Attack Duration</td> \n"
				+ "      </tr> \n" + "     </thead> \n"
				+ "     <tbody style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "      <tr style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;width:100%;height:0px\"> \n"
				+ "       <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\">1</td> \n"
				+ "       <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\">1</td> \n"
				+ "       <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\">0</td> \n"
				+ "       <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\">2562047788015h 12m</td> \n"
				+ "      </tr> \n" + "     </tbody> \n" + "    </table> \n" + "   </div> \n"
				+ "  </center> \n"
				+ "  <div class=\"reports-table\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;margin:1em auto 0 auto;padding:10px;min-width:1024px;width:85%;-moz-border-radius-bottomleft:3px;border-bottom-left-radius:3px;-moz-border-radius-bottomright:3px;border-bottom-right-radius:3px;-moz-border-radius-topright:3px;border-top-right-radius:3px;-moz-border-radius-topleft:3px;border-top-left-radius:3px;-webkit-print-color-adjust:exact\"> \n"
				+ "   <table style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;border-collapse:collapse;border-spacing:0;width:100%;margin:0px;padding:0px;border:1px solid rgb(195, 216, 216);background-color:rgb(255, 255, 255)\"> \n"
				+ "    <thead class=\"header\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "     <tr style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;width:100%\"> \n"
				+ "      <td rowspan=\"2\" class=\"bottom-border\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">#</td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Started</td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Lasted</td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Pain Level</td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Affected Activities</td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\"> Potential Triggers </td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Symptoms</td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Auras</td> \n"
				+ "      <td colspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Pain Positions</td> \n"
				+ "      <td rowspan=\"2\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Medication</td> \n"
				+ "      <td rowspan=\"2\" class=\"bottom-left-border\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\"> Non Drug Relief Methods </td> \n"
				+ "     </tr> \n"
				+ "     <tr class=\"subheading\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;width:100%\"> \n"
				+ "      <td width=\"7%\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Left</td> \n"
				+ "      <td width=\"7%\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;background-color:rgb(63, 121, 140);border:0px solid rgb(195, 216, 216);text-align:center;font-size:12px;border-width:0px 0px 1px 1px;font-weight:bold;color:rgb(255, 255, 255)\">Right</td> \n"
				+ "     </tr> \n" + "    </thead> \n"
				+ "    <tbody style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "     <tr style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;width:100%;height:0px\"> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\">1</td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> \n"
				+ "       <div style=\"align:center;padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "        <span style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> 1/1/70 00:00 </span>\n"
				+ "        <br style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\">Location: \n"
				+ "        <div style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\"> \n"
				+ "        </div> \n" + "       </div> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> Ongoing </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "      <td style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px\"> </td> \n"
				+ "     </tr> \n"
				+ "     <tr style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;width:100%;height:0px\"> \n"
				+ "      <td colspan=\"12\" class=\"notes\" style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;vertical-align:middle;border:1px solid rgb(195, 216, 216);border-width:0px 1px 1px 0px;text-align:center;padding:4px;font-size:12px;color:rgb(11, 39, 48);max-width:150px;text-align:left;padding-bottom:15px\"> <pre style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif;white-space:pre-wrap\"><strong style=\";padding:0;margin:0;color:rgb(63, 121, 140);font-family:&quot;Asap&quot;, sans-serif\">Notes:</strong> Some Test Notes</pre> </td> \n"
				+ "     </tr> \n" + "    </tbody> \n" + "   </table> \n" + "  </div>   \n"
				+ " </body>\n" + "</html>";

		HtmlToPdf.convertHtmlBytes(html.getBytes(), "t1.pdf", true);
	}
}
